import { Inter } from 'next/font/google'
import NavBar  from '../../Component/Navbar/NavBar3.jsx'
import  './globals.module.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ACP nextjs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        {/* <header>
          <title>{metadata.title}</title>
          <meta>{metadata.description}</meta>
        
        </header> */}
      
      <body>
      {/* <NavBar/> */}

        {children}
      
        </body>
    </html>
  )
}
